
- name: Set /etc/haproxy/haproxy.cfg
  template:
    src: "etc-haproxy-haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: haproxy -f %s -c
  notify: restart haproxy
  tags:
    - aspects_haproxy